"""empty message

Revision ID: 0f5305681809
Revises: 94f6e2a36a67
Create Date: 2024-06-27 07:46:12.619585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0f5305681809'
down_revision: Union[str, None] = '94f6e2a36a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('request', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('leads', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'created_at')
    op.drop_column('leads', 'request')
    # ### end Alembic commands ###
