"""empty message

Revision ID: 1ca3c7ed5d80
Revises: c949f9b00844
Create Date: 2024-10-21 16:57:57.146873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1ca3c7ed5d80'
down_revision: Union[str, None] = 'c949f9b00844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_installations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('app_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bot_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bot_scopes', sa.JSON(), nullable=True),
    sa.Column('bot_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bot_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enterprise_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enterprise_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enterprise_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('installed_at', sa.Float(), nullable=False),
    sa.Column('is_enterprise_install', sa.Boolean(), nullable=False),
    sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('token_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_scopes', sa.JSON(), nullable=True),
    sa.Column('user_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_installation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_foreign_key(None, 'slack_installations', ['slack_installation_id'], ['id'])
        batch_op.drop_column('slack_user_id')
        batch_op.drop_column('slack_bot_id')
        batch_op.drop_column('slack_bot_user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_bot_user_id', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('slack_bot_id', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('slack_user_id', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('slack_installation_id')

    op.drop_table('slack_installations')
    # ### end Alembic commands ###
