"""empty message

Revision ID: 24bbe7266ce5
Revises: 07256b8f260c
Create Date: 2024-02-20 21:27:08.440171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '24bbe7266ce5'
down_revision: Union[str, None] = '07256b8f260c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'tenant1'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'tenant_id',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'tenant1'::character varying"))
    # ### end Alembic commands ###
