"""empty message

Revision ID: 3dae8f5f4720
Revises: e1ed343e5562
Create Date: 2024-02-23 08:46:26.724101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '3dae8f5f4720'
down_revision: Union[str, None] = 'e1ed343e5562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('stage', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'new'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stage')
    # ### end Alembic commands ###
