"""empty message

Revision ID: 47b58f81639e
Revises: 124846ecf248
Create Date: 2024-04-14 10:55:16.194132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '47b58f81639e'
down_revision: Union[str, None] = 'e5ecc4c8c91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    print('hi')
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'test_prompt', new_column_name='prompts_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'prompts_json', new_column_name='test_prompt')
    # ### end Alembic commands ###
