"""empty message

Revision ID: 4a8be7c11619
Revises: ada60a594aab
Create Date: 2024-11-06 09:55:54.143641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '4a8be7c11619'
down_revision: Union[str, None] = 'ada60a594aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_slack_user_id'), ['slack_user_id'], unique=True)
        batch_op.drop_constraint('users_slack_installation_id_fkey', type_='foreignkey')
        batch_op.drop_column('slack_installation_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_installation_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_slack_installation_id_fkey', 'slack_installations', ['slack_installation_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_users_slack_user_id'))
        batch_op.drop_column('slack_user_id')

    # ### end Alembic commands ###
