"""empty message

Revision ID: 612be2597b79
Revises: fb84df8f8d4c
Create Date: 2024-03-19 21:04:49.219733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '612be2597b79'
down_revision: Union[str, None] = 'fb84df8f8d4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authsession', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_authsession_user_id'), 'authsession', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_authsession_user_id'), table_name='authsession')
    op.drop_column('authsession', 'user_id')
    # ### end Alembic commands ###
