"""empty message

Revision ID: 71ae7fb35e76
Revises: 26fe89b1e190
Create Date: 2024-10-21 11:57:45.308488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '71ae7fb35e76'
down_revision: Union[str, None] = '26fe89b1e190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_bot_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
        batch_op.drop_column('slack_access_token')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_access_token', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
        batch_op.drop_column('slack_bot_id')

    # ### end Alembic commands ###
