"""empty message

Revision ID: 854cb8906e2d
Revises: d0ff3be32413
Create Date: 2024-10-15 13:23:06.549630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '854cb8906e2d'
down_revision: Union[str, None] = 'd0ff3be32413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slack_user_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('slack_user_id')

    # ### end Alembic commands ###
