"""empty message

Revision ID: 9c4a3fac6d1c
Revises: 37aad3b9ef42
Create Date: 2024-08-02 16:03:10.584174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9c4a3fac6d1c'
down_revision: Union[str, None] = '37aad3b9ef42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('implicit_tools', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('agents', sa.Column('max_chat_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'max_chat_length')
    op.drop_column('agents', 'implicit_tools')
    # ### end Alembic commands ###
