"""empty message

Revision ID: a08cda3c4278
Revises: 65778ea73668
Create Date: 2024-03-19 12:01:41.113215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a08cda3c4278'
down_revision: Union[str, None] = '65778ea73668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authsession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiration', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authsession_session_id'), 'authsession', ['session_id'], unique=True)
    op.create_index(op.f('ix_authsession_user_id'), 'authsession', ['user_id'], unique=False)
    op.add_column('users', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'enabled')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'name')
    op.drop_column('users', 'email')
    op.drop_index(op.f('ix_authsession_user_id'), table_name='authsession')
    op.drop_index(op.f('ix_authsession_session_id'), table_name='authsession')
    op.drop_table('authsession')
    # ### end Alembic commands ###
