"""empty message

Revision ID: a12bcefcdf98
Revises: b5374f9878e1
Create Date: 2024-02-14 23:47:37.679228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a12bcefcdf98'
down_revision: Union[str, None] = 'b5374f9878e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gtoken_info_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('users', 'gtoken_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gtoken_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'gtoken_info_json')
    # ### end Alembic commands ###
