"""empty message

Revision ID: ac93ad9b7948
Revises: a12bcefcdf98
Create Date: 2024-02-16 15:14:23.626315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ac93ad9b7948'
down_revision: Union[str, None] = 'a12bcefcdf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_factory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secrets_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_factory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credential_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('agents', sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'tenant1'"), nullable=False))
    op.add_column('agents', sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'shared'"), nullable=False))
    op.add_column('users', sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'tenant1'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tenant_id')
    op.drop_column('agents', 'scope')
    op.drop_column('agents', 'tenant_id')
    op.drop_table('tools')
    op.drop_table('credentials')
    # ### end Alembic commands ###
