"""empty message

Revision ID: c0fa08cb0ca0
Revises: 9f2b081be91f
Create Date: 2024-06-13 16:14:00.573188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c0fa08cb0ca0'
down_revision: Union[str, None] = '9f2b081be91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('memories_json', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'memories_json')
    # ### end Alembic commands ###
