"""empty message

Revision ID: cc30848cb34f
Revises: bd227984734a
Create Date: 2024-02-16 16:03:34.348784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cc30848cb34f'
down_revision: Union[str, None] = 'bd227984734a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('credentials', sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'tenant1'"), nullable=False))
    op.create_foreign_key(None, 'credentials', 'users', ['user_id'], ['id'])
    op.add_column('tools', sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'tenant1'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'tenant_id')
    op.drop_constraint(None, 'credentials', type_='foreignkey')
    op.drop_column('credentials', 'tenant_id')
    op.drop_column('credentials', 'user_id')
    # ### end Alembic commands ###
