"""empty message

Revision ID: d5048969f5ba
Revises: d7fa668a7cb9
Create Date: 2024-08-13 16:05:24.444090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd5048969f5ba'
down_revision: Union[str, None] = 'd7fa668a7cb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), server_default='New org', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'name')
    # ### end Alembic commands ###
