"""empty message

Revision ID: e1ed343e5562
Revises: d90a61f931fb
Create Date: 2024-02-22 15:36:36.734272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e1ed343e5562'
down_revision: Union[str, None] = 'd90a61f931fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('test_prompt', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("''"), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'test_prompt')
    # ### end Alembic commands ###
