"""empty message

Revision ID: e2439f7f522a
Revises: 854cb8906e2d
Create Date: 2024-10-15 13:35:22.750269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2439f7f522a'
down_revision: Union[str, None] = '854cb8906e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_constraint('tools_agent_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'agents', ['agent_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tools_agent_id_fkey', 'agents', ['agent_id'], ['id'])

    # ### end Alembic commands ###
