"""empty message

Revision ID: e5ecc4c8c91a
Revises: e4838887da32
Create Date: 2024-04-23 08:05:00.246741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e5ecc4c8c91a'
down_revision: Union[str, None] = 'e4838887da32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('folders', sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('folders', sa.Column('parent_folder_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'folders', 'folders', ['parent_folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.drop_column('folders', 'parent_folder_id')
    op.drop_column('folders', 'slug')
    # ### end Alembic commands ###
