"""empty message

Revision ID: fb84df8f8d4c
Revises: a08cda3c4278
Create Date: 2024-03-19 21:04:09.224753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'fb84df8f8d4c'
down_revision: Union[str, None] = 'a08cda3c4278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authsession_user_id', table_name='authsession')
    op.drop_column('authsession', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authsession', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_authsession_user_id', 'authsession', ['user_id'], unique=False)
    # ### end Alembic commands ###
