"""empty message

Revision ID: 05ea3cd9e78f
Revises: a303610d176b
Create Date: 2024-10-17 22:45:58.689782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '05ea3cd9e78f'
down_revision: Union[str, None] = 'a303610d176b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_indexes', sa.Column('folder_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('doc_indexes', sa.Column('file_patterns', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_indexes', 'file_patterns')
    op.drop_column('doc_indexes', 'folder_ids')
    # ### end Alembic commands ###
