"""empty message

Revision ID: 0a1598f70b9d
Revises: f18b8086035b
Create Date: 2024-11-06 11:40:27.589577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '0a1598f70b9d'
down_revision: Union[str, None] = 'f18b8086035b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('enabled_indexes', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'enabled_indexes')
    # ### end Alembic commands ###
