"""empty message

Revision ID: 150c70b5dc2e
Revises: 1201b524d4df
Create Date: 2024-11-04 12:15:43.523367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '150c70b5dc2e'
down_revision: Union[str, None] = '1201b524d4df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_source_configs', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('doc_source_configs', sa.Column('doc_source_factory_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint('doc_source_configs_doc_source_id_fkey', 'doc_source_configs', type_='foreignkey')
    op.drop_column('doc_source_configs', 'doc_source_id')
    op.drop_table('doc_sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_sources',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tool_factory_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secrets_json', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='doc_sources_pkey')
    )
    op.add_column('doc_source_configs', sa.Column('doc_source_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('doc_source_configs_doc_source_id_fkey', 'doc_source_configs', 'doc_sources', ['doc_source_id'], ['id'])
    op.drop_column('doc_source_configs', 'doc_source_factory_id')
    op.drop_column('doc_source_configs', 'name')
    # ### end Alembic commands ###
