"""empty message

Revision ID: 2f14fd3daaa2
Revises: 05ea3cd9e78f
Create Date: 2024-10-17 22:52:36.375706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '2f14fd3daaa2'
down_revision: Union[str, None] = '05ea3cd9e78f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_indexes', sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('doc_indexes', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_indexes', 'user_id')
    op.drop_column('doc_indexes', 'tenant_id')
    # ### end Alembic commands ###
