"""empty message

Revision ID: 3d94000b4d4f
Revises: 382e51e49046
Create Date: 2024-10-24 22:08:39.169916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '3d94000b4d4f'
down_revision: Union[str, None] = '382e51e49046'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('tools', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'tools')
    # ### end Alembic commands ###
