"""Adding 'memories_json' column to agent table

Revision ID: 4a9da2320f21
Revises: d86d2818937e
Create Date: 2024-06-13 22:31:20.291254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '4a9da2320f21'
down_revision: Union[str, None] = 'd86d2818937e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('memories_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'memories_json')
    # ### end Alembic commands ###
