"""empty message

Revision ID: 5b5139fcc1ae
Revises: bd8f28a5acc5
Create Date: 2024-02-25 12:09:53.594817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added

# revision identifiers, used by Alembic.
revision: str = '5b5139fcc1ae'
down_revision: Union[str, None] = 'bd8f28a5acc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # create a fake agents record so we can add agent_id col to Run table
    op.execute("insert into agents (id, name, input_mode, trigger) values ('a1', 'placeholder','fit','Chat box')")
    op.add_column('run', sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("update run set agent_id = 'a1' where agent_id is null")
    op.alter_column('run', 'agent_id', nullable=False)
    op.create_foreign_key(None, 'run', 'agents', ['agent_id'], ['id'])
    op.drop_column('run', 'agent_spec')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('agent_spec', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'run', type_='foreignkey')
    op.drop_column('run', 'agent_id')
    # ### end Alembic commands ###
