"""empty message

Revision ID: 693ae09dc797
Revises: 2f14fd3daaa2
Create Date: 2024-10-21 08:04:35.314360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '693ae09dc797'
down_revision: Union[str, None] = '2f14fd3daaa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_source_configs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('doc_index_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('folder_ids', sa.JSON(), nullable=True),
    sa.Column('file_patterns', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['doc_index_id'], ['doc_indexes.id'], ),
    sa.ForeignKeyConstraint(['doc_source_id'], ['doc_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doc_source_configs')
    # ### end Alembic commands ###
