"""empty message

Revision ID: 722cd8129182
Revises: 5b5139fcc1ae
Create Date: 2024-02-25 20:22:34.405778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '722cd8129182'
down_revision: Union[str, None] = '5b5139fcc1ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('trigger_arg', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'trigger_arg')
    # ### end Alembic commands ###
