"""empty message

Revision ID: 822be8d2fe92
Revises: 8c33b10c2bc0
Create Date: 2024-08-01 22:36:42.125590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '822be8d2fe92'
down_revision: Union[str, None] = '8c33b10c2bc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('implicit_tools', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('agents', sa.Column('max_chat_length', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'max_chat_length')
    op.drop_column('agents', 'implicit_tools')
    # ### end Alembic commands ###
