"""empty message

Revision ID: 8c33b10c2bc0
Revises: 5bdc273cc60f
Create Date: 2024-07-22 16:54:53.781392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '8c33b10c2bc0'
down_revision: Union[str, None] = '5bdc273cc60f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_logs', sa.Column('version', sa.Integer(), server_default='2', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_logs', 'version')
    # ### end Alembic commands ###
