"""empty message

Revision ID: 8f4885c7a4f7
Revises: 12b381495e47
Create Date: 2024-11-01 10:48:52.041430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = '8f4885c7a4f7'
down_revision: Union[str, None] = '12b381495e47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_indexes', sa.Column('source_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_indexes', 'source_description')
    # ### end Alembic commands ###
