"""empty message

Revision ID: b103e0c542e8
Revises: 4a9da2320f21
Create Date: 2024-06-23 15:22:48.184943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'b103e0c542e8'
down_revision: Union[str, None] = '4a9da2320f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('input_tokens', sa.Integer(), server_default='0', nullable=True))
    op.add_column('run', sa.Column('output_tokens', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'output_tokens')
    op.drop_column('run', 'input_tokens')
    # ### end Alembic commands ###
