"""empty message

Revision ID: b40f446ca242
Revises: 759efe09d366
Create Date: 2024-10-22 22:32:13.235281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'b40f446ca242'
down_revision: Union[str, None] = '759efe09d366'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_indexes', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_indexes', 'error_message')
    # ### end Alembic commands ###
