"""empty message

Revision ID: b8ee64a0bf68
Revises: f3a590393799
Create Date: 2024-03-22 15:15:53.491507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'b8ee64a0bf68'
down_revision: Union[str, None] = 'f3a590393799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailmsgsprocessed', sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('run_logs', sa.Column('lc_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run_logs', 'lc_run_id')
    op.drop_column('emailmsgsprocessed', 'agent_id')
    # ### end Alembic commands ###
