"""empty message

Revision ID: f18b8086035b
Revises: 150c70b5dc2e
Create Date: 2024-11-04 14:10:40.716372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision: str = 'f18b8086035b'
down_revision: Union[str, None] = '150c70b5dc2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doc_source_configs', sa.Column('provider_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doc_source_configs', 'provider_data')
    # ### end Alembic commands ###
