"""Create CompressedHistoryMessage table

Revision ID: f3a8b9c01d2e
Revises: 5bdc273cc60f
Create Date: 2024-06-23 15:22:48.184943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3a8b9c01d2e'
down_revision: Union[str, None] = '822be8d2fe92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compressedhistorymessage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('compressed_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('original_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('compressed_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('message_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('tokens_original', sa.Integer(), nullable=False),
        sa.Column('tokens_compressed', sa.Integer(), nullable=False),
        sa.Column('compression_ratio', sa.Float(), nullable=False),
        sa.Column('compression_algorithm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compressedhistorymessage_compressed_id'), 'compressedhistorymessage', ['compressed_id'], unique=False)
    


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compressedhistorymessage_compressed_id'), table_name='compressedhistorymessage')
    op.drop_table('compressedhistorymessage')